### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by davidmind** [lindell/remote-function#5]
Hi, @lindell am a graphics designer. I will like to know if you want me to create a new logo for your project.

**Comment by lindell** [comment]
Hi @davidmind. I would love that! 😄 I was thinking about creating some sort of logo when launching this project but realized it would be awful.

**Comment by davidmind** [comment]
Ok, I will go and work on my sketch. While I come back with feed back.

**Comment by davidmind** [comment]
Hi, @lindell sorry for the delay. After making several sketch, this is what i came up with.

![1557861172770.jpg](https://cdn.steemitimages.com/DQmWJoydf13zYZ67PMvagJgkyDndwdK4hpAVSKxnWKHPvdZ/1557861172770.jpg)

**Comment by davidmind** [comment]
@lindell are you there?

**Comment by lindell** [comment]
Yes, sorry for the wait. And thanks again for taking the time to make this. 

The biggest feedback I have is that I'm not really sure what the logo is supposed to represent, even with the description. What I see is the symbol of a wireless phone, maybe the logo could be based on the communication between two entities? :)

**Comment by davidmind** [comment]
Ok, i notice the project focus on call forwarding directly from the server.
But i will work on something else.

**Comment by davidmind** [comment]
@lindell sorry it take a long time for me to reply. I have been making use of different element combination. Most of them seems not to work. Today after making a new sketch I end up with this. You can make suggestion on colors and other things 
![remote-call-pres.png](https://cdn.steemitimages.com/DQmeCH3Hrk8ZkACP8SsHYoCipK6mxHbmDXPoGv6efy5jPfQ/remote-call-pres.png)

**Comment by davidmind** [comment]
@lindell are you there?

**Comment by davidmind** [comment]
@lindell are you there?

**Comment by lindell** [comment]
Hi again, I really appreciate the effort.

But unfortunately I'm not a fan of this approach to symbology. I would not made the connection to what remote-function is about if all parts wasn't explained.

As I said before. I really appreciate the effort. But I don't think these logo designs will work.
